version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch_container
    env_file:
      - .env.development
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

volumes:
  pgdata:
