apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  POSTGRES_USER: cHJvZF91c2Vy  # Base64 de "prod_user"
  POSTGRES_PASSWORD: cHJvZF9wYXNzd29yZA==  # Base64 de "prod_password"
  POSTGRES_DB: cHJvZF9kYXRhYmFzZQ==  # Base64 de "prod_database"
